Le_Domain='adguard.kuehl.one'
Le_Alt='paperless.kuehl.one,homeassistant.kuehl.one'
Le_Webroot='dns_desec'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_ChallengeAlias='klarwasser.dedyn.io,'
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/3301876825/507184125845'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/3301876825/507184125845'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/0524e10902757acd34e14a6aa55c6e9ee09e'
Le_CertCreateTime='1777886381'
Le_CertCreateTimeStr='2026-05-04T09:19:41Z'
Le_NextRenewTimeStr='2026-07-02T12:24:04Z'
Le_NextRenewTime='1782995044'
Le_RealCertPath='/etc/letsencrypt/live/kuehl.one/cert.pem'
Le_RealCACertPath=''
Le_RealKeyPath='/etc/letsencrypt/live/kuehl.one/privkey.pem'
Le_ReloadCmd='__ACME_BASE64__START_ZG9ja2VyIHJlc3RhcnQgcGFwZXJsZXNzLWNhZGR5LTE=__ACME_BASE64__END_'
Le_RealFullChainPath='/etc/letsencrypt/live/kuehl.one/fullchain.pem'
