

#LOG_FILE="/home/toto/.acme.sh/acme.sh.log"
#LOG_LEVEL=1

#AUTO_UPGRADE="1"

#NO_TIMESTAMP=1

    
ACCOUNT_EMAIL='pitcher.bike-1o@icloud.com'
UPGRADE_HASH='7735cdf3abe84bce8c1e37e7fa46c71e38606262'
SAVED_DEDYN_TOKEN=''
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games'
