CA_EMAIL='pitcher.bike-1o@icloud.com'
CA_EAB_KEY_ID='bMARsHJSwi3RlGWmOOfLvQ'
CA_EAB_HMAC_KEY='JZw8OujeJNHqlAbEJT5JP1xfK9Q5GUjYoCMi8B7rHYgrsQ6AMNr8RXDD8U9wod-4YGkGzJuAy-mdxbji2CnJxQ'
ACCOUNT_URL='https://acme.zerossl.com/v2/DV90/account/bMARsHJSwi3RlGWmOOfLvQ'
CA_KEY_HASH='C3tWFcm/Gq/YU3k6yyYEDJEANFUBfWk7UxMKyt+p80Q='
